# disclaimer: this was all written by claude. i have no idea how github actions work
# and am not particularly interested in learning for the time being

name: Haskell CI

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2.8.1
        with:
          ghc-version: "9.10.1"
          cabal-version: "3.12.1.0"

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-cabal
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build and test (non-release)
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: cabal build --enable-tests --enable-benchmarks all

      - name: Build release binary
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cabal build --enable-optimization=2
          mkdir -p release
          cp $(cabal list-bin tomo) release/

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
